# Generated by Django 4.0.4 on 2022-09-01 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='', upload_to='profile_image'),
            preserve_default=False,
        ),
    ]
