# Generated by Django 4.0.4 on 2022-09-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_modelo', models.CharField(max_length=50)),
                ('año', models.FloatField()),
                ('transmision', models.BooleanField()),
                ('sku', models.CharField(max_length=30)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Camiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_modelo', models.CharField(max_length=50)),
                ('año', models.FloatField()),
                ('capacidad', models.CharField(max_length=30)),
                ('sku', models.CharField(max_length=30)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Motos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_modelo', models.CharField(max_length=50)),
                ('año', models.FloatField()),
                ('tipo', models.CharField(max_length=20)),
                ('sku', models.CharField(max_length=30)),
                ('precio', models.FloatField()),
            ],
        ),
    ]
