# Generated by Django 4.0.4 on 2022-09-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autos',
            name='sku',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='camiones',
            name='sku',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='motos',
            name='sku',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
