# Generated by Django 4.0.5 on 2022-09-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_alter_autos_sku_alter_camiones_sku_alter_motos_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autos',
            name='transmision',
            field=models.BooleanField(blank=True),
        ),
    ]
