# Generated by Django 4.0.5 on 2022-09-03 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0005_cars_motorcycles_trucks_delete_autos_delete_camiones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='motorcycles',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trucks',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
