# Generated by Django 4.0.4 on 2022-09-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0006_cars_is_active_motorcycles_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cars'),
        ),
        migrations.AddField(
            model_name='motorcycles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='motorcycles'),
        ),
        migrations.AddField(
            model_name='trucks',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trucks'),
        ),
    ]
