# Generated by Django 4.0.4 on 2022-09-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0007_cars_image_motorcycles_image_trucks_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='image',
            field=models.ImageField(null=True, upload_to='cars'),
        ),
        migrations.AlterField(
            model_name='motorcycles',
            name='image',
            field=models.ImageField(null=True, upload_to='motorcycles'),
        ),
        migrations.AlterField(
            model_name='trucks',
            name='image',
            field=models.ImageField(null=True, upload_to='trucks'),
        ),
    ]
