# Generated by Django 4.0.4 on 2022-09-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0008_alter_cars_image_alter_motorcycles_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cars'),
        ),
    ]
